package net.nettapepro.dal.object;

// Generated 11-nov-2009 17:17:46 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Backupsetitem generated by hbm2java
 */
public class Backupsetitem implements java.io.Serializable {

	private Integer backupsetitemid;
	private Backupset backupset;
	private String path;
	private Short type;
	private Boolean backup;
	private Boolean isfolder;
	private String root;
	private Set backupitems = new HashSet(0);
	private Set backupitems_1 = new HashSet(0);

	public Backupsetitem() {
	}

	public Backupsetitem(Backupset backupset, String path, Short type,
			Boolean backup, Boolean isfolder, String root, Set backupitems,
			Set backupitems_1) {
		this.backupset = backupset;
		this.path = path;
		this.type = type;
		this.backup = backup;
		this.isfolder = isfolder;
		this.root = root;
		this.backupitems = backupitems;
		this.backupitems_1 = backupitems_1;
	}

	public Integer getBackupsetitemid() {
		return this.backupsetitemid;
	}

	public void setBackupsetitemid(Integer backupsetitemid) {
		this.backupsetitemid = backupsetitemid;
	}

	public Backupset getBackupset() {
		return this.backupset;
	}

	public void setBackupset(Backupset backupset) {
		this.backupset = backupset;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public Short getType() {
		return this.type;
	}

	public void setType(Short type) {
		this.type = type;
	}

	public Boolean getBackup() {
		return this.backup;
	}

	public void setBackup(Boolean backup) {
		this.backup = backup;
	}

	public Boolean getIsfolder() {
		return this.isfolder;
	}

	public void setIsfolder(Boolean isfolder) {
		this.isfolder = isfolder;
	}

	public String getRoot() {
		return this.root;
	}

	public void setRoot(String root) {
		this.root = root;
	}

	public Set getBackupitems() {
		return this.backupitems;
	}

	public void setBackupitems(Set backupitems) {
		this.backupitems = backupitems;
	}

	public Set getBackupitems_1() {
		return this.backupitems_1;
	}

	public void setBackupitems_1(Set backupitems_1) {
		this.backupitems_1 = backupitems_1;
	}

}
