package net.nettapepro.dal.object;

// Generated 11-nov-2009 17:17:46 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Backupitem generated by hbm2java
 */
public class Backupitem implements java.io.Serializable {

	private Integer backupitemid;
	private Backup backup;
	private Backupsetitem backupsetitem;
	private String path;
	private Short type;
	private Date datetime;
	private Long position;
	private Long length;
	private Boolean isdeltas;
	private String root;
	private Boolean folder;

	public Backupitem() {}

	public Backupitem(	Backup backup,
						Backupsetitem backupsetitem,
						String path,
						Short type,
						Date datetime,
						Long position,
						Long length,
						Boolean isdeltas,
						String root,
						Boolean folder) {
		this.backup = backup;
		this.backupsetitem = backupsetitem;
		this.path = path;
		this.type = type;
		this.datetime = datetime;
		this.position = position;
		this.length = length;
		this.isdeltas = isdeltas;
		this.root = root;
		this.folder = folder;
	}

	public Integer getBackupitemid() {
		return this.backupitemid;
	}

	public void setBackupitemid(Integer backupitemid) {
		this.backupitemid = backupitemid;
	}

	public Backup getBackup() {
		return this.backup;
	}

	public void setBackup(Backup backup) {
		this.backup = backup;
	}

	public Backupsetitem getBackupsetitem() {
		return this.backupsetitem;
	}

	public void setBackupsetitem(Backupsetitem backupsetitem) {
		this.backupsetitem = backupsetitem;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public Short getType() {
		return this.type;
	}

	public void setType(Short type) {
		this.type = type;
	}

	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	public Long getPosition() {
		return this.position;
	}

	public void setPosition(Long position) {
		this.position = position;
	}

	public Long getLength() {
		return this.length;
	}

	public void setLength(Long length) {
		this.length = length;
	}

	public Boolean getIsdeltas() {
		return this.isdeltas;
	}

	public void setIsdeltas(Boolean isdeltas) {
		this.isdeltas = isdeltas;
	}

	public String getRoot() {
		return this.root;
	}

	public void setRoot(String root) {
		this.root = root;
	}

	public Boolean getFolder() {
		return this.folder;
	}

	public void setFolder(Boolean folder) {
		this.folder = folder;
	}

}
