package net.nettapepro.dal.object;

// Generated 11-nov-2009 17:17:46 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Backup generated by hbm2java
 */
public class Backup implements java.io.Serializable {

	private Integer backupid;
	private Backupset backupset;
	private String name;
	private Date datetime;
	private Date datetimeended;
	private Integer serverid;
	private Set backupitems = new HashSet(0);
	private Set backupitems_1 = new HashSet(0);

	public Backup() {
	}

	public Backup(Backupset backupset, String name, Date datetime,
			Date datetimeended, Integer serverid, Set backupitems,
			Set backupitems_1) {
		this.backupset = backupset;
		this.name = name;
		this.datetime = datetime;
		this.datetimeended = datetimeended;
		this.serverid = serverid;
		this.backupitems = backupitems;
		this.backupitems_1 = backupitems_1;
	}

	public Integer getBackupid() {
		return this.backupid;
	}

	public void setBackupid(Integer backupid) {
		this.backupid = backupid;
	}

	public Backupset getBackupset() {
		return this.backupset;
	}

	public void setBackupset(Backupset backupset) {
		this.backupset = backupset;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	public Date getDatetimeended() {
		return this.datetimeended;
	}

	public void setDatetimeended(Date datetimeended) {
		this.datetimeended = datetimeended;
	}

	public Integer getServerid() {
		return this.serverid;
	}

	public void setServerid(Integer serverid) {
		this.serverid = serverid;
	}

	public Set getBackupitems() {
		return this.backupitems;
	}

	public void setBackupitems(Set backupitems) {
		this.backupitems = backupitems;
	}

	public Set getBackupitems_1() {
		return this.backupitems_1;
	}

	public void setBackupitems_1(Set backupitems_1) {
		this.backupitems_1 = backupitems_1;
	}

}
