package net.nettapepro.dal.object;

// Generated 11-nov-2009 17:17:46 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Backupset generated by hbm2java
 */
public class Backupset implements java.io.Serializable {

	private Integer backupsetid;
	private Integer clientid;
	private String name;
	private Date datecreated;
	private Date datedeleted;
	private Date datedeactivated;
	private Boolean active;
	private Boolean deleted;
	private Boolean retention;
	private Boolean filepermissions;
	private Boolean continuousprotection;
	private Integer cpinterval;
	private Short type;
	private Boolean isdeltas;
	private Set filters = new HashSet(0);
	private Set schedules = new HashSet(0);
	private Set backupsetitems = new HashSet(0);
	private Set backups = new HashSet(0);
	private Set backups_1 = new HashSet(0);
	private Set iprestrictions = new HashSet(0);
	private Set schedules_1 = new HashSet(0);
	private Set backupsetitems_1 = new HashSet(0);
	private Set iprestrictions_1 = new HashSet(0);
	private Set filters_1 = new HashSet(0);

	public Backupset() {
	}

	public Backupset(Integer clientid, String name, Date datecreated,
			Date datedeleted, Date datedeactivated, Boolean active,
			Boolean deleted, Boolean retention, Boolean filepermissions,
			Boolean continuousprotection, Integer cpinterval, Short type,
			Boolean isdeltas, Set filters, Set schedules, Set backupsetitems,
			Set backups, Set backups_1, Set iprestrictions, Set schedules_1,
			Set backupsetitems_1, Set iprestrictions_1, Set filters_1) {
		this.clientid = clientid;
		this.name = name;
		this.datecreated = datecreated;
		this.datedeleted = datedeleted;
		this.datedeactivated = datedeactivated;
		this.active = active;
		this.deleted = deleted;
		this.retention = retention;
		this.filepermissions = filepermissions;
		this.continuousprotection = continuousprotection;
		this.cpinterval = cpinterval;
		this.type = type;
		this.isdeltas = isdeltas;
		this.filters = filters;
		this.schedules = schedules;
		this.backupsetitems = backupsetitems;
		this.backups = backups;
		this.backups_1 = backups_1;
		this.iprestrictions = iprestrictions;
		this.schedules_1 = schedules_1;
		this.backupsetitems_1 = backupsetitems_1;
		this.iprestrictions_1 = iprestrictions_1;
		this.filters_1 = filters_1;
	}

	public Integer getBackupsetid() {
		return this.backupsetid;
	}

	public void setBackupsetid(Integer backupsetid) {
		this.backupsetid = backupsetid;
	}

	public Integer getClientid() {
		return this.clientid;
	}

	public void setClientid(Integer clientid) {
		this.clientid = clientid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	public Date getDatedeleted() {
		return this.datedeleted;
	}

	public void setDatedeleted(Date datedeleted) {
		this.datedeleted = datedeleted;
	}

	public Date getDatedeactivated() {
		return this.datedeactivated;
	}

	public void setDatedeactivated(Date datedeactivated) {
		this.datedeactivated = datedeactivated;
	}

	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	public Boolean getRetention() {
		return this.retention;
	}

	public void setRetention(Boolean retention) {
		this.retention = retention;
	}

	public Boolean getFilepermissions() {
		return this.filepermissions;
	}

	public void setFilepermissions(Boolean filepermissions) {
		this.filepermissions = filepermissions;
	}

	public Boolean getContinuousprotection() {
		return this.continuousprotection;
	}

	public void setContinuousprotection(Boolean continuousprotection) {
		this.continuousprotection = continuousprotection;
	}

	public Integer getCpinterval() {
		return this.cpinterval;
	}

	public void setCpinterval(Integer cpinterval) {
		this.cpinterval = cpinterval;
	}

	public Short getType() {
		return this.type;
	}

	public void setType(Short type) {
		this.type = type;
	}

	public Boolean getIsdeltas() {
		return this.isdeltas;
	}

	public void setIsdeltas(Boolean isdeltas) {
		this.isdeltas = isdeltas;
	}

	public Set getFilters() {
		return this.filters;
	}

	public void setFilters(Set filters) {
		this.filters = filters;
	}

	public Set getSchedules() {
		return this.schedules;
	}

	public void setSchedules(Set schedules) {
		this.schedules = schedules;
	}

	public Set getBackupsetitems() {
		return this.backupsetitems;
	}

	public void setBackupsetitems(Set backupsetitems) {
		this.backupsetitems = backupsetitems;
	}

	public Set getBackups() {
		return this.backups;
	}

	public void setBackups(Set backups) {
		this.backups = backups;
	}

	public Set getBackups_1() {
		return this.backups_1;
	}

	public void setBackups_1(Set backups_1) {
		this.backups_1 = backups_1;
	}

	public Set getIprestrictions() {
		return this.iprestrictions;
	}

	public void setIprestrictions(Set iprestrictions) {
		this.iprestrictions = iprestrictions;
	}

	public Set getSchedules_1() {
		return this.schedules_1;
	}

	public void setSchedules_1(Set schedules_1) {
		this.schedules_1 = schedules_1;
	}

	public Set getBackupsetitems_1() {
		return this.backupsetitems_1;
	}

	public void setBackupsetitems_1(Set backupsetitems_1) {
		this.backupsetitems_1 = backupsetitems_1;
	}

	public Set getIprestrictions_1() {
		return this.iprestrictions_1;
	}

	public void setIprestrictions_1(Set iprestrictions_1) {
		this.iprestrictions_1 = iprestrictions_1;
	}

	public Set getFilters_1() {
		return this.filters_1;
	}

	public void setFilters_1(Set filters_1) {
		this.filters_1 = filters_1;
	}

}
