package net.nettapepro.dal.object;

// Generated 11-nov-2009 17:17:46 by Hibernate Tools 3.2.4.GA

/**
 * Criteria generated by hbm2java
 */
public class Criteria implements java.io.Serializable {

	private Integer criteriaid;
	private Filter filter;
	private String pattern;
	private Short type;
	private Boolean matchCase;

	public Criteria() {
	}

	public Criteria(Filter filter, String pattern, Short type, Boolean matchase) {
		this.filter = filter;
		this.pattern = pattern;
		this.type = type;
		this.matchCase = matchase;
	}

	public Integer getCriteriaid() {
		return this.criteriaid;
	}

	public void setCriteriaid(Integer criteriaid) {
		this.criteriaid = criteriaid;
	}

	public Filter getFilter() {
		return this.filter;
	}

	public void setFilter(Filter filter) {
		this.filter = filter;
	}

	public String getPattern() {
		return this.pattern;
	}

	public void setPattern(String pattern) {
		this.pattern = pattern;
	}

	public Short getType() {
		return this.type;
	}

	public void setType(Short type) {
		this.type = type;
	}

	public Boolean getMatchCase() {
		return this.matchCase;
	}

	public void setMatchCase(Boolean matchCase) {
		this.matchCase = matchCase;
	}
}
