package net.nettapepro.dal.object;

// Generated 11-nov-2009 17:17:46 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Filter generated by hbm2java
 */
public class Filter implements java.io.Serializable {

	private Integer filterid;
	private Backupset backupset;
	private Restore restore;
	private String name;
	private Boolean include;
	private String toppath;
	private Set criterias = new HashSet(0);
	private Set criterias_1 = new HashSet(0);

	public Filter() {
	}

	public Filter(Backupset backupset, String name, Boolean include,
			String toppath, Set criterias, Set criterias_1) {
		this.backupset = backupset;
		this.name = name;
		this.include = include;
		this.toppath = toppath;
		this.criterias = criterias;
		this.criterias_1 = criterias_1;
	}

	public Filter(Restore restore, String name, Boolean include,
			String toppath, Set criterias, Set criterias_1) {
		this.restore = restore;
		this.name = name;
		this.include = include;
		this.toppath = toppath;
		this.criterias = criterias;
		this.criterias_1 = criterias_1;
	}

	public Integer getFilterid() {
		return this.filterid;
	}

	public void setFilterid(Integer filterid) {
		this.filterid = filterid;
	}

	public Backupset getBackupset() {
		return this.backupset;
	}

	public void setBackupset(Backupset backupset) {
		this.backupset = backupset;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getInclude() {
		return this.include;
	}

	public void setInclude(Boolean include) {
		this.include = include;
	}

	public String getToppath() {
		return this.toppath;
	}

	public void setToppath(String toppath) {
		this.toppath = toppath;
	}

	public Set getCriterias() {
		return this.criterias;
	}

	public void setCriterias(Set criterias) {
		this.criterias = criterias;
	}

	public Set getCriterias_1() {
		return this.criterias_1;
	}

	public void setCriterias_1(Set criterias_1) {
		this.criterias_1 = criterias_1;
	}

	public Restore getRestore() {
		return restore;
	}

	public void setRestore(Restore restore) {
		this.restore = restore;
	}

}
