package net.nettapepro.dal.object;

// Generated 11-nov-2009 17:17:46 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Restoreitem generated by hbm2java
 */
public class Restoreitem implements java.io.Serializable {

	private Integer restoreitemid;
	private Restore restore;
	private String path;
	private Short type;
	private Date datetime;

	public Restoreitem() {
	}

	public Restoreitem(Restore restore, String path, Short type, Date datetime) {
		this.restore = restore;
		this.path = path;
		this.type = type;
		this.datetime = datetime;
	}

	public Integer getRestoreitemid() {
		return this.restoreitemid;
	}

	public void setRestoreitemid(Integer restoreitemid) {
		this.restoreitemid = restoreitemid;
	}

	public Restore getRestore() {
		return this.restore;
	}

	public void setRestore(Restore restore) {
		this.restore = restore;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public Short getType() {
		return this.type;
	}

	public void setType(Short type) {
		this.type = type;
	}

	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

}
