package net.nettapepro.dal.object;

// Generated 11-nov-2009 17:17:46 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Restore generated by hbm2java
 */
public class Restore implements java.io.Serializable {

	private Integer restoreid;
	private Date datetime;
	private Date datetimeended;
	private String restorepath;
	private Boolean overwrite;
	private Boolean restorepermissions;
	private Set restoreitems = new HashSet(0);
	private Set restoreitems_1 = new HashSet(0);
	private Filter filter;

	public Restore() {
	}

	public Restore(Date datetime, Date datetimeended, String restorepath,
			Boolean overwrite, Boolean restorepermissions, Set restoreitems,
			Set restoreitems_1, Filter filter) {
		this.datetime = datetime;
		this.datetimeended = datetimeended;
		this.restorepath = restorepath;
		this.overwrite = overwrite;
		this.restorepermissions = restorepermissions;
		this.restoreitems = restoreitems;
		this.restoreitems_1 = restoreitems_1;
		this.filter = filter;
	}

	public Integer getRestoreid() {
		return this.restoreid;
	}

	public void setRestoreid(Integer restoreid) {
		this.restoreid = restoreid;
	}

	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	public Date getDatetimeended() {
		return this.datetimeended;
	}

	public void setDatetimeended(Date datetimeended) {
		this.datetimeended = datetimeended;
	}

	public String getRestorepath() {
		return this.restorepath;
	}

	public void setRestorepath(String restorepath) {
		this.restorepath = restorepath;
	}

	public Boolean getOverwrite() {
		return this.overwrite;
	}

	public void setOverwrite(Boolean overwrite) {
		this.overwrite = overwrite;
	}

	public Boolean getRestorepermissions() {
		return this.restorepermissions;
	}

	public void setRestorepermissions(Boolean restorepermissions) {
		this.restorepermissions = restorepermissions;
	}

	public Set getRestoreitems() {
		return this.restoreitems;
	}

	public void setRestoreitems(Set restoreitems) {
		this.restoreitems = restoreitems;
	}

	public Set getRestoreitems_1() {
		return this.restoreitems_1;
	}

	public void setRestoreitems_1(Set restoreitems_1) {
		this.restoreitems_1 = restoreitems_1;
	}

	public Filter getFilter() {
		return filter;
	}

	public void setFilter(Filter filter) {
		this.filter = filter;
	}

}
